### ISSUE TITLE
Uninformative RequirementParseError

### ISSUE THREAD

**Issue by anayebi** [neuroailab/tfutils#57]
When using tfutils, if I run a script outside of a github repo, I get the following (uninformative) error. This error should be updated to be more informative.

`INFO:tfutils:module tensorflow.python.training.learning_rate_decay not in a git repo, checking package version
INFO:tfutils:module __main__ not in a git repo, checking package version
Traceback (most recent call last):
  File "train_alexnet_kanef_imnet_example.py", line 533, in <module>
    train_model()
  File "train_alexnet_kanef_imnet_example.py", line 529, in train_model
    base.train_from_params(**params)
  File "/home/anayebi/.local/lib/python2.7/site-packages/tfutils/base.py", line 165, in __init__
    self.sonified_params = sonify(self.params)
  File "/home/anayebi/.local/lib/python2.7/site-packages/tfutils/utils.py", line 147, in sonify
    for k, v in arg.items()])
  File "/home/anayebi/.local/lib/python2.7/site-packages/tfutils/utils.py", line 147, in sonify
    for k, v in arg.items()])
  File "/home/anayebi/.local/lib/python2.7/site-packages/tfutils/utils.py", line 147, in sonify
    for k, v in arg.items()])
  File "/home/anayebi/.local/lib/python2.7/site-packages/tfutils/utils.py", line 147, in sonify
    for k, v in arg.items()])
  File "/home/anayebi/.local/lib/python2.7/site-packages/tfutils/utils.py", line 162, in sonify
    rval = version_check_and_info(mod)
  File "/home/anayebi/.local/lib/python2.7/site-packages/tfutils/utils.py", line 62, in version_check_and_info
    info = version_info(module)
  File "/home/anayebi/.local/lib/python2.7/site-packages/tfutils/utils.py", line 41, in version_info
    info = pkg_resources.get_distribution(pkgname)
  File "/home/anayebi/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 550, in get_distribution
    dist = Requirement.parse(dist)
  File "/home/anayebi/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2935, in parse
    req, = parse_requirements(s)
  File "/home/anayebi/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2883, in parse_requirements
    yield Requirement(line)
  File "/home/anayebi/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2892, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid requirement, parse error at "'__main__'"`

**Comment by yamins81** [comment]
ok this is resolved now with a (more informative) warning.
